export const CONFIRM_ACCOUNT = 'CONFIRM_ACCOUNT'
export const CONFIRM_ACCOUNT_SUCCESS = 'CONFIRM_ACCOUNT_SUCCESS'
export const CONFIRM_ACCOUNT_FAIL = 'CONFIRM_ACCOUNT_FAIL'

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REQUEST_PASSWORD_CHANGE = 'REQUEST_PASSWORD_CHANGE'
export const REQUEST_PASSWORD_CHANGE_SUCCESS = 'REQUEST_PASSWORD_CHANGE_SUCCESS'
export const REQUEST_PASSWORD_CHANGE_FAIL = 'REQUEST_PASSWORD_CHANGE_FAIL'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
