export const CONFIRM_ACCOUNT = 'CONFIRM_ACCOUNT'
export const CONFIRM_ACCOUNT_SUCCESS = 'CONFIRM_ACCOUNT_SUCCESS'
export const CONFIRM_ACCOUNT_FAILURE = 'CONFIRM_ACCOUNT_FAILURE'

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CREATE_ACCOUNT_VALIDATION_FAILURE = 'CREATE_ACCOUNT_VALIDATION_FAILURE'
export const CREATE_ACCOUNT_CLIENT_FAILURE = 'CREATE_ACCOUNT_CLIENT_FAILURE'
export const CREATE_ACCOUNT_SERVER_FAILURE = 'CREATE_ACCOUNT_SERVER_FAILURE'
