export const CONFIRM_ACCOUNT = 'CONFIRM_ACCOUNT'
export const CONFIRM_ACCOUNT_SUCCESS = 'CONFIRM_ACCOUNT_SUCCESS'
export const CONFIRM_ACCOUNT_FAIL = 'CONFIRM_ACCOUNT_FAIL'

export const REQUEST_ACCOUNT = 'REQUEST_ACCOUNT'
export const REQUEST_ACCOUNT_SUCCESS = 'REQUEST_ACCOUNT_SUCCESS'
export const REQUEST_ACCOUNT_FAIL = 'REQUEST_ACCOUNT_FAIL'
